### ISSUE TITLE
Full Text indexing not working after tika changes

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13868]
You are unable to search pdfs, word docs after the externalization of Tika.

For example, search the content store for "viewtools" on demo and vs. local.

We need to check pdfs, docs, pptx, for both content store and for site search

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/13981
https://github.com/dotCMS/enterprise-2.x/pull/602

Tika plugin:
https://github.com/dotCMS/plugin-com.dotcms.tika

**Comment by jgambarios** [comment]
Fixed but a new starter is required.

**Comment by bryanboza** [comment]
New starter required

**Comment by jgambarios** [comment]
We have a new starter in master

**Comment by bryanboza** [comment]
Tested in demo and locally and we still having problems with some specific words, as in viewtools in the example.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14299

**Comment by jgambarios** [comment]
Fixed but before to send it to QA a new starter is required.

**Comment by wezell** [comment]
We need two properties in code:
```
boolean regenerateMissingMetadata = Config
				.getBooleanProperty("regenerate.missing.metadata.on.reindex", true);

boolean alwaysRegenerateMetadata = Config
	                .getBooleanProperty("always.regenerate.metadata.on.reindex", false);

```

We need to add `always.regenerate.metadata.on.reindex` to dotmarketing-config.properties

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14410

**Comment by bryanboza** [comment]
Fixed, tested on the last master code and now this works as expected.

**Comment by wezell** [comment]
If customer uses metadata searching, e.g. fulltext searching, and are upgrading from < 5.0, they should either delete the metadata files out of their /assets dir and reindex OR set `always.regenerate.metadata.on.reindex=true` and reindex.  This can force the reindeexation process to run slowly and only needs to be done once  - the property should be set back to false after reindexing
 `always.regenerate.metadata.on.reindex=false`
