### ISSUE TITLE
Don't allow user to edit a template from the layout designer

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13942]
As a stakeholder I don't want user to be able to edit a template from the layout designer.

## Expected Behavior
When user is editing a page and click "Layout" it goes directly to edit the layout.

## Current Behavior
When user is editing a page and click "Layout" it show a dialog where the user can select if want to edit the layout or the template of the page.

## Possible Solution
Maybe we can add a param to [this component](https://github.com/dotCMS/core-web/blob/master/src/app/portlets/dot-edit-page/layout/dot-edit-layout/dot-edit-layout.component.html#L4) like ```[editTemplate]="true/false"```

And also we should get rid of [this](https://github.com/dotCMS/core-web/blob/master/src/app/portlets/dot-edit-page/layout/dot-edit-layout/dot-edit-layout.component.html#L1)

## Steps to Reproduce (for bugs)
1. Login
2. Edit a page
3. Click on "Layout" in the sidebar
4. See there is a dialog

## Acceptance Criteria

1. Not show dialog to select edit layout or template
2. Remove the functionality to edit the advanced template
3. Remove the checkbox of "Save as template"
4. Work in all the supported browsers (don't forget IE11 and iPad)
5. Multilanguage
6. Unit test

**Comment by fmontes** [comment]
@hmoreras I merged this and QA, but is missing one AC: Remove the checkbox of "Save as template"

**Comment by fmontes** [comment]
Is broken when user can't edit the page, example bill@dotcms.com

**Comment by bryanboza** [comment]
We are unable to see this tab if you are as limited user, since now this modification is only for the page, I should have only edit permissions on the page to allow modify the layout. 
SC: https://screencast.com/t/Lwj3nfEStN

**Comment by bryanboza** [comment]
We still having problems here, now we are able to see the tab as limited user, but we have an error when you try to made some modification as this user 
SC: https://screencast.com/t/cfvdfymAn

**Comment by fmontes** [comment]
The issue is related with the renderHTML endpoint and not the nav bar, so I create an issue for that: https://github.com/dotCMS/core/issues/14148
