### ISSUE TITLE
Template Builder: Removing Box breaks content page

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#27646]
### Parent Issue

https://github.com/dotCMS/core/issues/26413

### Problem Statement

Removing only the box, not the row, makes content disappear

### Steps to Reproduce

https://github.com/dotCMS/core/assets/5278970/639f4539-8fff-4f6f-8fdb-f4b9dfdba17e

### Acceptance Criteria

Content should be kept regardless modifications to the template/layout.

### dotCMS Version

master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/114930

**Comment by fmontes** [comment]
Tentative fixed here: https://github.com/dotCMS/core/issues/27689

**Comment by fmontes** [comment]
@erickgonzalez check now in master... we might fixed in the mentioned ticket.

Also we found another issue while working: https://github.com/dotCMS/core/issues/27816

**Comment by freddyDOTCMS** [comment]
Fix in https://github.com/dotCMS/core/pull/28128

**Comment by dsilvam** [comment]
Removing a container is still making content disappear

https://github.com/dotCMS/core/assets/1576794/298c7d63-847e-40c3-b341-b245ea22c821

**Comment by freddyDOTCMS** [comment]
PR: https://github.com/dotCMS/core/pull/28350

**Comment by weiyiwang-dotcms** [comment]
Hi team,

I was still able to reproduce the issue in v24.05.20, which I believe should have the fix for this.

I recorded the below screen recording.

I made a page with 5 pieces of content, arranged in two rows
Using the layout tab, I added two additional rows and added boxes in each of those rows
Once I switched back to the content tab, the content was missing
The content was still missing also in the edit mode of the page.

https://github.com/dotCMS/core/assets/136110669/e7fcb0ab-f68e-4bef-a0bc-994d07e62843
