### ISSUE TITLE
UVE not showing published page

### ISSUE THREAD

**Issue by mboutillette-dotcms** [dotCMS/core#31701]
### Problem Statement

In UVE, when on a page in Edit mode, when I navigate via the dropdown in the top left to Published selection, the screen tells me there is no published page - even though there is.  When I refresh the browser it shows me the published page.  See screen grab.

I have not been able to reproduce in the demo instance, it is happening in the demopm instance only.

https://github.com/user-attachments/assets/2d5d18c9-2a3d-4a7b-b7ea-81d186fd8ab3

### Steps to Reproduce

Navigate to Site / Pages
Select any page that is already published
Click on Draft in the top left to initiate the dropdown
Click on Published selection
You will see a message that tells you 'Nothing Live Here Yet'
Refresh your browser and the published page will show up

### Acceptance Criteria

When navigating to the Published selection, the published page should show up

### dotCMS Version

Current
In the demopm instance

### Proposed Objective

Customer Success

### Proposed Priority

Priority 2 - Important

**Comment by KevinDavilaDotCMS** [comment]
# Findings

I tested this in both the demo environment and locally (using the latest from main), but I couldn't reproduce the issue.

From what I can see, the problem seems to be related to backend session handling. The request is sent correctly, but the response returns a 404. However, when copying the request and running it through Postman or the browser, the response is 200, and the data loads as expected.

Additionally, that environment doesn’t have the latest changes made to UVE. Now, when accessing LIVE, the publishDate query parameter is no longer sent by default. This might actually resolve the issue in the demo environment.

It's likely that this was already fixed as part of the FTM stabilization process or improvements in UVE. I’d recommend updating the server version, as this issue is not present in main.

**Comment by nollymar** [comment]
I will close this issue, as we couldn't reproduce it in the latest version

**Comment by mboutillette-dotcms** [comment]
Hi @nollymar and @KevinDavilaDotCMS , I have updated the demopm instance to 25.04.08 and the site is still behaving in the same way.  I tried to replicate this in other places but have not been able to as of yet.  It happens for every page, so I think it is something to do with the site maybe?

**Comment by mboutillette-dotcms** [comment]
One more update, I seemed to have fixed the copy issue, it looks like it had something to do with version of the home page that was archived.  I removed the archived home page and the page that was published then was able to be copied.  Not sure if I could reproduce that again if I tried!  Anyway, the other issue is still there with the UVE not showing the published page.

**Comment by nollymar** [comment]
We will take a look @mboutillette-dotcms . Thanks for letting us know

**Comment by mboutillette-dotcms** [comment]
@nollymar and @KevinDavilaDotCMS - Will fixed it!!   Looks like it was something to do with a template or something in the Applications folder so he pushed a new one there from demo site and it is working now.  Thank you for your help, sorry to run you around like that!
