### ISSUE TITLE
Pushing working version of content publishes it if it ALSO has a live version

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#8784]
Version: 3.5
Ticket Ref: https://goo.gl/k6PkqQ

If you publish a piece of content that was previously live (has a live version in its history) but the current version is saved (yellow, working) on the sender: the receiver will basically get the last inode for that piece of content but show it BOTH live and working.

*Here is the current behavior:*
* If you push a working piece of content that has NO published version it its history, it'll push as a working piece of content
* if you push a working piece of content that was AT ONE POINT published, it'll push it as both a working and published version (matching the working inode of the sender)

*To reproduce:*
* create a piece of content, publish it
* edit that piece of content, save it [ now you have two different versions of that piece of content in different states]
* push that piece of content
* compare the piece of content's history and status on the receiver vs sender (see below)

![screen shot 2016-03-23 at 12 14 23 pm](https://cloud.githubusercontent.com/assets/1823543/13994736/8d1f3fee-f0fc-11e5-9bee-3644e706328a.png)

**Comment by aotearoan** [comment]
+1

This looks similar to https://my.dotcms.com/ticket/leonteq-37, please add the described test case when fixing.

Thanks.

**Comment by levosgien** [comment]
Yes I've commented on the ticket, please note that I've also fixed your link so that it doesn't expose the client's name (all tickets have a public URL). Thanks.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/357

**Comment by bryanboza** [comment]
Unable to recreate after the fix... 
Testing info:
Sender: master-3.5 // Postgres // FF
Receiver: master-3.5 // MySQL // Chrome

**Comment by oarrietadotcms** [comment]
We are still having this problem, steps to reproduce:

1. Create a Content Generic contentlet. Save and Publish.
2. Push Publish that contentlet. (Wait until the PP is done)
3. In the Sender, unpublish the contentlet.
4. Push Publish that contentlet. (Wait until the PP is done).
5. If you go into the Content Tab, you will see the contentlet unpublished.
6. Go to System -> Query Tool -> Lucene Query: +live:true / Sort: modDate desc
7. You will see that the contentlet in the index is still live.

Client ticket: https://my.dotcms.com/tickets/detail.dot?id=4253c464-04f2-4d61-abfa-a63bb8c0a58b

**Comment by oarrietadotcms** [comment]
See the proposed fix in client ticket: Lines 209, 225-238

**Comment by joseorsini** [comment]
Tested fix on 3.5 proposed by client on https://my.dotcms.com/tickets/detail.dot?id=4253c464-04f2-4d61-abfa-a63bb8c0a58b (from this Gist https://gist.github.com/oarrietadotcms/0581fffdd29e7589062b8bd89409f1a8) REST API reflects the right state of the content once it's pushed.

**Comment by joseorsini** [comment]
Updated fix https://github.com/dotCMS/enterprise-2.x/pull/379
