### ISSUE TITLE
Push Publishing user Fails

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9242]
Reproduced in 3.5. Steps.

1. Create a user:
  - Full Name: Dummy User.
  - Email Address: dummy@gmail.com

2. Push the new user to Receiver side (clicking on the Push Publish button). Push works.

3. Edit the user you created on the Sender side. 

4. Push the user by clicking on the Push Publish button. Push does not proceed. Checking the Publishing Queue, only one record is tied to the user, which it was the first time it was pushed. Checking the Audit/Status list would retrieve the same information. Cleaning up the push publishing tables in DB and the Push history don't seem to do the trick

5. Add the user to a bundle by clicking on the "Add to Bundle" button. Put any name for the bundle. It will create an empty bundle that can only be deleted. 

-- 

Right-click actions on the Users list (Individual push or adding users to a bundle) work as expected, so the events on the available Buttons (Push Publish/Add to Bundle) once you select an user are not working as expected.

**Comment by joseorsini** [comment]
Another issue: 

1. Create a user
  - Email Address: Dummy@dotcms.com
  - Full Name: Dummy User.

2. Push it via right click to a Receiver environment. Push works as expected. 

3. Edit the user in Sender side. Change email address to "Dummy@gmail.com".

4. Push the edited user to Receiver mode. Push fails: 

Stacktrace: 
```
[20/06/16 14:59:00:157 UTC] INFO rest.PublishThread: Started bundle publish process
[20/06/16 14:59:00:176 UTC] INFO business.UserFactoryLiferayImpl: User already exists with this ID
[20/06/16 14:59:00:178 UTC] ERROR business.PublisherAPIImpl: Error Publishing Bundle: null
com.dotcms.publishing.DotPublishingException
at com.dotcms.enterprise.publishing.remote.handler.UserHandler.handle(SourceFile:150) ~[ee-gaf7f4f0.jar:?]
at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:161) [dotcms_3.5_g14af2ce.jar:?]
at com.dotcms.rest.PublishThread.run(PublishThread.java:41) [dotcms_3.5_g14af2ce.jar:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: com.dotmarketing.business.DuplicateUserException
at com.dotmarketing.business.UserFactoryLiferayImpl.createUser(UserFactoryLiferayImpl.java:108) ~[dotcms_3.5_g14af2ce.jar:?]
at com.dotmarketing.business.UserAPIImpl.createUser(UserAPIImpl.java:112) ~[dotcms_3.5_g14af2ce.jar:?]
at com.dotcms.enterprise.publishing.remote.handler.UserHandler.handle(SourceFile:110) ~[ee-gaf7f4f0.jar:?]
... 3 more
Caused by: com.liferay.portal.DuplicateUserIdException
at com.liferay.portal.ejb.UserLocalManagerImpl.validate(UserLocalManagerImpl.java:559) ~[dotcms_3.5_g14af2ce.jar:?]
at com.liferay.portal.ejb.UserLocalManagerImpl.addUser(UserLocalManagerImpl.java:103) ~[dotcms_3.5_g14af2ce.jar:?]
at com.liferay.portal.ejb.UserLocalManagerUtil.addUser(UserLocalManagerUtil.java:48) ~[dotcms_3.5_g14af2ce.jar:?]
at com.dotmarketing.business.UserFactoryLiferayImpl.createUser(UserFactoryLiferayImpl.java:102) ~[dotcms_3.5_g14af2ce.jar:?]
at com.dotmarketing.business.UserAPIImpl.createUser(UserAPIImpl.java:112) ~[dotcms_3.5_g14af2ce.jar:?]
at com.dotcms.enterprise.publishing.remote.handler.UserHandler.handle(SourceFile:110) ~[ee-gaf7f4f0.jar:?]
... 3 more
[20/06/16 14:59:00:183 UTC] ERROR lang.String: Error Publishing: com.dotcms.publishing.DotPublishingException
[20/06/16 14:59:00:183 UTC] INFO rest.PublishThread: Finished bundle publish process
[20/06/16 15:00:00:202 UTC] INFO rest.PublishThread: Started bundle publish process
[20/06/16 15:00:00:220 UTC] INFO business.UserFactoryLiferayImpl: User already exists with this ID
[20/06/16 15:00:00:220 UTC] ERROR business.PublisherAPIImpl: Error Publishing Bundle: null
com.dotcms.publishing.DotPublishingException
at com.dotcms.enterprise.publishing.remote.handler.UserHandler.handle(SourceFile:150) ~[ee-gaf7f4f0.jar:?]
at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:161) [dotcms_3.5_g14af2ce.jar:?]
at com.dotcms.rest.PublishThread.run(PublishThread.java:41) [dotcms_3.5_g14af2ce.jar:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: com.dotmarketing.business.DuplicateUserException
at com.dotmarketing.business.UserFactoryLiferayImpl.createUser(UserFactoryLiferayImpl.java:108) ~[dotcms_3.5_g14af2ce.jar:?]
at com.dotmarketing.business.UserAPIImpl.createUser(UserAPIImpl.java:112) ~[dotcms_3.5_g14af2ce.jar:?]
at com.dotcms.enterprise.publishing.remote.handler.UserHandler.handle(SourceFile:110) ~[ee-gaf7f4f0.jar:?]
... 3 more
Caused by: com.liferay.portal.DuplicateUserIdException
at com.liferay.portal.ejb.UserLocalManagerImpl.validate(UserLocalManagerImpl.java:559) ~[dotcms_3.5_g14af2ce.jar:?]
at com.liferay.portal.ejb.UserLocalManagerImpl.addUser(UserLocalManagerImpl.java:103) ~[dotcms_3.5_g14af2ce.jar:?]
at com.liferay.portal.ejb.UserLocalManagerUtil.addUser(UserLocalManagerUtil.java:48) ~[dotcms_3.5_g14af2ce.jar:?]
at com.dotmarketing.business.UserFactoryLiferayImpl.createUser(UserFactoryLiferayImpl.java:102) ~[dotcms_3.5_g14af2ce.jar:?]
at com.dotmarketing.business.UserAPIImpl.createUser(UserAPIImpl.java:112) ~[dotcms_3.5_g14af2ce.jar:?]
at com.dotcms.enterprise.publishing.remote.handler.UserHandler.handle(SourceFile:110) ~[ee-gaf7f4f0.jar:?]
... 3 more
[20/06/16 15:00:00:223 UTC] ERROR lang.String: Error Publishing: com.dotcms.publishing.DotPublishingException
[20/06/16 15:00:00:223 UTC] INFO rest.PublishThread: Finished bundle publish process
[20/06/16 15:00:04:610 UTC] INFO cache.VirtualLinksCache: mapping: dotcms.com:/docs/latest -> /docs/latest/table-of-contents
[20/06/16 15:01:00:167 UTC] INFO rest.PublishThread: Started bundle publish process
[20/06/16 15:01:00:186 UTC] INFO business.UserFactoryLiferayImpl: User already exists with this ID
[20/06/16 15:01:00:186 UTC] ERROR business.PublisherAPIImpl: Error Publishing Bundle: null
com.dotcms.publishing.DotPublishingException
at com.dotcms.enterprise.publishing.remote.handler.UserHandler.handle(SourceFile:150) ~[ee-gaf7f4f0.jar:?]
at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:161) [dotcms_3.5_g14af2ce.jar:?]
at com.dotcms.rest.PublishThread.run(PublishThread.java:41) [dotcms_3.5_g14af2ce.jar:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: com.dotmarketing.business.DuplicateUserException
at com.dotmarketing.business.UserFactoryLiferayImpl.createUser(UserFactoryLiferayImpl.java:108) ~[dotcms_3.5_g14af2ce.jar:?]
at com.dotmarketing.business.UserAPIImpl.createUser(UserAPIImpl.java:112) ~[dotcms_3.5_g14af2ce.jar:?]
at com.dotcms.enterprise.publishing.remote.handler.UserHandler.handle(SourceFile:110) ~[ee-gaf7f4f0.jar:?]
... 3 more
Caused by: com.liferay.portal.DuplicateUserIdException
at com.liferay.portal.ejb.UserLocalManagerImpl.validate(UserLocalManagerImpl.java:559) ~[dotcms_3.5_g14af2ce.jar:?]
at com.liferay.portal.ejb.UserLocalManagerImpl.addUser(UserLocalManagerImpl.java:103) ~[dotcms_3.5_g14af2ce.jar:?]
at com.liferay.portal.ejb.UserLocalManagerUtil.addUser(UserLocalManagerUtil.java:48) ~[dotcms_3.5_g14af2ce.jar:?]
at com.dotmarketing.business.UserFactoryLiferayImpl.createUser(UserFactoryLiferayImpl.java:102) ~[dotcms_3.5_g14af2ce.jar:?]
at com.dotmarketing.business.UserAPIImpl.createUser(UserAPIImpl.java:112) ~[dotcms_3.5_g14af2ce.jar:?]
at com.dotcms.enterprise.publishing.remote.handler.UserHandler.handle(SourceFile:110) ~[ee-gaf7f4f0.jar:?]
... 3 more
[20/06/16 15:01:00:191 UTC] ERROR lang.String: Error Publishing: com.dotcms.publishing.DotPublishingException
[20/06/16 15:01:00:191 UTC] INFO rest.PublishThread: Finished bundle publish process
``` 

On a default dotCMS environment, Frontend/Backend authentication for each Push Publishing endpoint may be set to the user's email Address. Users Lookup during Push Publishing takes this into consideration, so this means that if you changed a User's Email Address and then push it, the Lookup won't find them remotely. In other words, it would assume it's a new user, however, the userId remains the same, therefore the exception is thrown and the user is not pushed.

**Comment by jtesser** [comment]
make sure to test bi-directional testing

**Comment by oarrietadotcms** [comment]
For clarification, the functionality on the [first comment](https://github.com/dotCMS/core/issues/9242#issue-161217407) is working just fine and as [documented](http://dotcms.com/docs/latest/publishing-users). It is not really intuitive but works as [required](https://github.com/dotCMS/core/issues/2929#issue-14729742). 

Also when testing this, you have set up the **"Created after"** property correctly. dotCMS 3.6 doesn't have a _moddate_ for users so it doesn't take into account the modified date of a specific user, just the creation date. In dotCMS 3.7 we could improve this logic because the _moddate_ was added as part of the JWT feature.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/381

**Comment by oarrietadotcms** [comment]
I implemented a fallback when looking for the user by email. I thought this was the best approach in order to not break this requirement: https://github.com/dotCMS/core/issues/3159

**Comment by dsilvam** [comment]
Doc needs to be updated: http://dotcms.com/docs/latest/publishing-users, since it says that it is possible to multi-select users from the list at left and then click the button next to add user and push them. That button (Push Publish) only works for pushing users modified after a given date, it does not interact with the list of users.

**Comment by john-thomas-dotcms** [comment]
Doc updated: http://dotcms.com/docs/latest/publishing-users

**Comment by nollymar** [comment]
One scenario is still failing.

Configured environment:
Host A --> osX,  postgres
Host B --> Windows, postgres

Both server where configured to send/receive to each other (bi-directional way)

First test: **Sender:** Host A / **Receiver:** Host B
_In Host A:_
1)  Add a new user and push. Result: OK
2)  Modify user's e-mail and push. Result: OK

Second test: **Sender:** Host B / **Receiver:** Host A
_In Host B:_
1) Modify the e-mail of the user received in the First test.
2) Add a new user and specify: roles, permissions, additional info.
3) Add both user to a bundle (modified user and new user)
4) Push bundle to Receiver (Host A). Result: Fail

![push-user](https://cloud.githubusercontent.com/assets/8741395/17670263/b4ef7038-62d6-11e6-8cf4-3206634107ff.png)


Sender's log: https://gist.github.com/nollymar/0ac5d7a6f919debc9ad63dc35ccd059f

**Comment by nollymar** [comment]
A similar scenario was tested on 3.5 and the bi-directional test worked correctly. However, for Second test just the modified user was added to the bundle and pushed because it was not possible to create a new user

**Comment by oarrietadotcms** [comment]
I tested again and it is working just fine in my local, same steps that @nollymar, even the bidirectional works.

I think your env is not sync with the latest ee code, because [the stack-trace](https://gist.github.com/nollymar/d1074e09985afef1a4e73a6769e53109#file-receiver-user-push-log-L17-L18) in your log [doesn't match the logic in place after my fix](https://github.com/dotCMS/enterprise-2.x/blob/master-3.6/src/com/dotcms/enterprise/publishing/remote/handler/UserHandler.java#L110). 

Maybe you need a:
```
./gradlew --refresh-dependencies clean
```
